LISTA_MODULOS = ['despesas', 'contratosdeterceiros', 'receitas', 'benspatrimoniados', 'saldos', 'itensdenotafiscal']

LISTA_ACOES = ['alteracao', 'exclusao', 'inclusao']

LISTA_ATRIBUTOS_SALDOS = [
    'VALOR EM CONTA CORRENTE', 'APLICACAO FINANCEIRA', 'PROVISAO', 'VALOR EM ESPECIE', 'IMAGEM DO EXTRATO'
]

LISTA_ATRIBUTOS_DESPESAS = [
    'VALOR PAGO', 'VALOR DO DOCUMENTO', 'RUBRICA', 'DESCRICAO', 'CONTA CORRENTE',
    'UNIDADE', 'IDENTIFICADOR BANCARIO', 'NUMERO DO DOCUMENTO',
    'CNPJ', 'RAZAO SOCIAL', 'DATA DE EMISSAO', 'TIPO DE DOCUMENTO', 'CPF', 'NOME',
    'DATA DE VENCIMENTO', 'DATA DE PAGAMENTO', 'DATA DE APURACAO', 'TIPO DE DESPESA',
    'SERIE', 'NUMERO DE PARCELAS', 'CODIGO FISCAL', 'PARCELA PAGA'
]

LISTA_ATRIBUTOS_CONTRATOS_DE_TERCEIROS = [
    'NOME DO ARQUIVO', 'SERVICO', 'UNIDADE', 'VIGENCIA', 'VALOR MENSAL', 'RAZAO SOCIAL',
    'CNPJ', 'CPF', 'NOME', 'MES INICIO', 'MES FIM', 'ANO INICIO', 'ANO FIM'
]

LISTA_ATRIBUTOS_BENS_PATRIMONIADOS = [
    'NOME ARQUIVO IMAGEM', 'VIDA UTIL', 'VINCULACAO', 'SETOR DESTINO', 'NOTA FISCAL', 'DESCRICAO',
    'TIPO', 'CONTROLE', 'RAZAO SOCIAL', 'CNPJ', 'QUANTIDADE', 'VALOR', 'UNIDADE'
]

LISTA_ATRIBUTOS_ITENS_DE_NOTA_FISCAL = [
    'NUMERO DA NOTA FISCAL', 'CODIGO DO MATERIAL', 'CODIGO DO SERVICO', 'DESCRICAO', 'UNIDADE DE MEDIDA',
    'QUANTIDADE', 'VALOR UNITARIO', 'VALOR TOTAL', 'MES DE REFERENCIA', 'ANO DE REFERENCIA',
    'FORNECEDOR', 'OBSERVACAO'
]

LISTA_ATRIBUTOS_RECEITAS = [
    'CONTRATO DE GESTAO PARTE FIXA', 'REPASSE CONTRATO DE GESTAO PARTE VARIAVEL 1',
    'REPASSE CONTRATO DE GESTAO PARTE VARIAVEL 2', 'REPASSE CONTRATO DE GESTAO PARTE VARIAVEL 3',
    'TERMO ADITIVO ADICIONAL CUSTEIO', 'TERMO ADITIVO ADICIONAL INVESTIMENTO',
    'RESULTADO DE APLICACAO FINANCEIRA', 'ESTORNO DE DESPESAS',
    'OBTENCAO DE RECURSOS EXTERNOS', 'RETORNO DE EMPRESTIMO REALIZADO A OUTRO CONTRATO',
    'EMPRESTIMO TOMADO DE OUTRO CONTRATO', 'TRANSFERENCIAS ENTRE CONTAS DE PROVISIONAMENTO E EXECUCAO',
    'TRANSFERENCIA DE PROVISIONAMENTO DE COLABORADORES ORIUNDOS DE OUTRO CONTRATO E OU UNIDADE'
]

LISTA_ATRIBUTOS_FOLHA_DE_PAGAMENTO = [
    'VINCULO',
    'UNIDADE',
    'MES DE COMPETENCIA',
    'ANO DE COMPETENCIA',
    'CARGA HORARIA EFETIVA',
    'PERCENTUAL DE RATEIO',
    'DATA LICENCA INICIO',
    'DATA LICENCA FIM',
    'SALARIO BASE PROVENTOS',
    'FERIAS PROVENTOS',
    '13 SALARIO PROVENTOS',
    'REEMBOLSO PROVENTOS',
    'HORAS EXTRAS PROVENTOS',
    'PLANTAO EXTRA PROVENTOS',
    'INSALUBRIDADE PROVENTOS',
    'PERICULOSIDADE PROVENTOS',
    'ADICIONAL NOTURNO PROVENTOS',
    'GRATIFICACAO DE TITULACAO PROVENTOS',
    'PREMIACOES PROVENTOS',
    'BONIFICACAO VARIAVEL 3 PROVENTOS',
    'SALARIO FAMILIA PROVENTOS',
    'BOLSA AUXILIO PROVENTOS',
    'GRATIFICACOES PROVENTOS',
    'LICENCA MATERNIDADE PROVENTOS',
    'DESCANSO SEMANAL REMUNERADO PROVENTOS',
    'ASSISTENCIA FINANCEIRA COMPLEMENTAR UNIAO PROVENTOS',
    'INSUFICIENCIA SALDO PROVENTOS',
    'HONORARIOS PROVENTOS',
    'FALTA DESCONTOS',
    'ATRASOS DESCONTOS',
    'ADIANTAMENTOS DESCONTOS',
    'CONTRIBUICAO SINDICAL DESCONTOS',
    'VALE ALIMENTACAO DESCONTOS',
    'VALE REFEICAO DESCONTOS',
    'VALE TRANSPORTE DESCONTOS',
    'VALE COMBUSTIVEL DESCONTOS',
    'PENSAO ALIMENTICIA DESCONTOS',
    'CONVENIO MEDICO DESCONTOS',
    'EMPRESTIMO CONSIGNADO DESCONTOS',
    'INSS DESCONTOS',
    'IRRF DESCONTOS',
    '2 VIA CARTAO DESCONTOS',
    'MULTA DIVERSAS DESCONTOS',
    'JUDICIAL DESCONTOS',
    'INSUFICIENCIA SALDO DESCONTOS',
    'ISSQN DESCONTOS',
    'BASE CALCULO INSS ENCARGOS PATRONAIS GRUPO A',
    'BASE CALCULO FGTS ENCARGOS PATRONAIS GRUPO A',
    'BASE CALCULO PIS ENCARGOS PATRONAIS GRUPO A',
    'PIS ENCARGOS PATRONAIS GRUPO A',
    'SESI SESC ENCARGOS PATRONAIS GRUPO A',
    'SENAI SENAC ENCARGOS PATRONAIS GRUPO A',
    'INCRA ENCARGOS PATRONAIS GRUPO A',
    'SALARIO EDUCACAO ENCARGOS PATRONAIS GRUPO A',
    'SAT ENCARGOS PATRONAIS GRUPO A',
    'SEBRAE ENCARGOS PATRONAIS GRUPO A',
    'VALE ALIMENTACAO BENEFICIOS',
    'VALE REFEICAO BENEFICIOS',
    'VALE TRANSPORTE BENEFICIOS',
    'VALE COMBUSTIVEL BENEFICIOS',
    'AUXILIO CRECHE BENEFICIOS',
    'PLANO DE SAUDE BENEFICIOS',
    'AJUDA DE CUSTO MOBILIDADE BENEFICIOS',
    'SEGURO DE VIDA BENEFICIOS',
    'PREVIDENCIA PRIVADA BENEFICIOS',
    'FERIAS RESCISAO',
    'FERIAS E ABONO RESCISAO',
    '13 SALARIO RESCISAO',
    'AVISO PREVIO RESCISAO',
    'AVISO PREVIO INDENIZADO RESCISAO',
    '13 SALARIO INDENIZADO RESCISAO',
    'MULTA FGTS RESCISAO',
    'REMUNERACAO LIQUIDA',
    'DESPESA TOTAL',
]

LISTA_ATRIBUTOS_PROVISIONAMENTO = [
    'VINCULO',
    'UNIDADE',
    'MES DE COMPETENCIA',
    'ANO DE COMPETENCIA',
    '13 SALARIO GRUPO B',
    'ABONO DE FERIAS GRUPO B',
    'FERIAS PROPORCIONAIS DEMISSAO GRUPO B',
    'FERIAS INTEGRAIS GRUPO B',
    'AVISO PREVIO GRUPO C',
    'AVISO PREVIO INDENIZADO GRUPO C',
    '13 SALARIO GRUPO C',
    'FERIAS E ABONO CONSTITUCIONAL GRUPO C',
    'MULTA FGTS GRUPO D',
    'INCIDENCIA DE A SOBRE B C GRUPO E',
    'FERIAS BAIXAS',
    '13 SALARIO BAIXAS',
    'AVISO PREVIO RECISAO BAIXAS',
    'AVISO PREVIO INDENIZADO RECISAO BAIXAS',
    '13 SALARIO RECISAO BAIXAS',
    'FERIAS E ABONO RECISAO BAIXAS',
    'MULTA FGTS RECISAO BAIXAS',
]

CONFIGURACOES_MODULOS = {
    'modulo_despesas': {
        'cabecalho_str': 'D;COD_OS;COD_UNIDADE;COD_CONTRATO;ANO_MES_REF;TIPO;CODIGO;CNPJ;RAZAO;CPF;NOME;NUM_DOCUMENTO;SERIE;DESCRICAO;DATA_EMISSAO;DATA_VENCIMENTO;DATA_PAGAMENTO;DATA_APURACAO;VALOR_DOCUMENTO;VALOR_PAGO;DESPESA;RUBRICA;BANCO;AGENCIA;CONTA_CORRENTE;PMT_PAGA;QTDE_PMT;IDENT_BANCARIO;FLAG_JUSTIFICATIVA',
        'datas_abreviadas': ['ANO_MES_REF'],
        'datas_completas': ['DATA_EMISSAO', 'DATA_VENCIMENTO', 'DATA_PAGAMENTO', 'DATA_APURACAO'],
        'campos_obrigatorios': ["NUM_DOCUMENTO", "SERIE", "COD_OS", "COD_UNIDADE", "COD_CONTRATO", "ANO_MES_REF", "TIPO", "DESCRICAO", "DATA_VENCIMENTO", "DATA_PAGAMENTO", "DATA_APURACAO", "VALOR_DOCUMENTO", "VALOR_PAGO", "DESPESA", "RUBRICA", "BANCO", "AGENCIA", "CONTA_CORRENTE", "PMT_PAGA", "QTDE_PMT", "IDENT_BANCARIO", "FLAG_JUSTIFICATIVA"],
        'campos_monetarios': ['VALOR_DOCUMENTO', 'VALOR_PAGO'],
        'limites_tamanho': {
            "RAZAO": 100,
            "NOME": 100,
            "DESCRICAO": 150,
            "NUM_DOCUMENTO": 20,
            "SERIE": 3,
            "DESPESA": 50,
            "IDENT_BANCARIO": 100
        }
    },
    'modulo_bens_patrimoniados': {
        'cabecalho_str': 'COD_OS;COD_UNIDADE;COD_CONTRATO;ANO_MES_REF;NUM_CONTROLE_OS;NUM_CONTROLE_GOV;COD_TIPO;BEM_TIPO;DESCRICAO_NF;CNPJ;FORNECEDOR;QUANTIDADE;NF;DATA_AQUISICAO;VIDA_UTIL;VALOR;VINCULACAO;SETOR_DESTINO;IMG_NF',
        'datas_abreviadas': ['ANO_MES_REF'],
        'datas_completas': ['DATA_AQUISICAO'],
        'campos_obrigatorios': ["COD_OS", "COD_UNIDADE", "COD_CONTRATO", "ANO_MES_REF", "NUM_CONTROLE_OS", "COD_TIPO", "BEM_TIPO", "DESCRICAO_NF", "CNPJ", "FORNECEDOR", "QUANTIDADE", "NF", "DATA_AQUISICAO", "VIDA_UTIL", "VALOR", "VINCULACAO", "IMG_NF"],
        'campos_monetarios': ['VALOR'],
        'limites_tamanho': {
            "DESCRICAO_NF": 255,
            "FORNECEDOR": 255,
            "NF": 20,
            "VINCULACAO": 255,
            "SETOR_DESTINO": 100
        }
    },
    'modulo_saldos': {
        'cabecalho_str': 'COD_OS;COD_UNIDADE;COD_CONTRATO;ANO_MES_REF;BANCO;AGENCIA;CONTA_CORRENTE;VL_CONTA_CORRENTE;VL_APL_FINANCEIRA;VL_CONTA_PROVISAO;VL_EM_ESPECIE;EXTRATO',
        'datas_abreviadas': ['ANO_MES_REF'],
        'datas_completas': [],
        'campos_obrigatorios': ["COD_OS", "COD_UNIDADE", "COD_CONTRATO", "ANO_MES_REF", "BANCO", "AGENCIA", "CONTA_CORRENTE", "VL_CONTA_CORRENTE", "VL_APL_FINANCEIRA", "VL_CONTA_PROVISAO", "VL_EM_ESPECIE", "EXTRATO"],
        'campos_monetarios': ['VL_CONTA_CORRENTE', 'VL_APL_FINANCEIRA', 'VL_CONTA_PROVISAO', 'VL_EM_ESPECIE'],
        'limites_tamanho': {}
    },
    'modulo_contratos_de_terceiros': {
        'cabecalho_str': 'D;COD_OS;COD_UNIDADE;COD_CONTRATO;RAZAO_SOCIAL;CNPJ;SERVICO;VALOR_MES;VIGENCIA;CONTRATO_ANO_MES_INICIO;CONTRATO_ANO_MES_FIM;REF_TRI;REF_ANO_MES;IMG_CONTRATO',
        'datas_abreviadas': ['CONTRATO_ANO_MES_INICIO', 'CONTRATO_ANO_MES_FIM', 'REF_TRI'],
        'datas_completas': ['REF_ANO_MES'],
        'campos_obrigatorios': ["COD_OS", "COD_UNIDADE", "COD_CONTRATO", "RAZAO_SOCIAL", "CNPJ", "SERVICO", "VALOR_MES", "VIGENCIA", "CONTRATO_ANO_MES_INICIO", "CONTRATO_ANO_MES_FIM", "REF_TRI", "REF_ANO_MES", "IMG_CONTRATO"],
        'campos_monetarios': ['VALOR_MES'],
        'limites_tamanho': {
            "RAZAO_SOCIAL": 100
        }
    },
    'modulo_fornecedores': {
        'cabecalho_str': 'CNPJ_CPF;NOME_FORNECEDOR;TIPO;CONTATO;ENDERECO;NUMERO;COMPLEMENTO;CEP;BAIRRO;MUNICIPIO;UF;REFERENCIA;FONE_1;RAMAL_1;FONE_2;RAMAL_2;FAX;EMAIL',
        'datas_abreviadas': [],
        'datas_completas': [],
        'campos_obrigatorios': ["CNPJ_CPF", "NOME_FORNECEDOR", "TIPO", "ENDERECO", "NUMERO", "CEP", "BAIRRO"],
        'campos_monetarios': [],
        'limites_tamanho': {}
    },
    'modulo_itens_nota_fiscal': {
        'cabecalho_str': 'NUM_OS;COD_MAT_SERV;DESC_MAT_SERV;UNID_MED;PREC_UNIT;QTD;VLR_TOT_ITEM;NF;CNPJ_FORN;MAT_OU_SERV;MES_ANO;OBS',
        'datas_abreviadas': ["MES_ANO"],
        'datas_completas': [],
        'campos_obrigatorios': ["NUM_OS", "COD_MAT_SERV", "DESC_MAT_SERV", "UNID_MED", "PREC_UNIT", "QTD", "VLR_TOT_ITEM", "NF", "CNPJ_FORN", "MAT_OU_SERV", "MES_ANO"],
        'campos_monetarios': ["PREC_UNIT", "VLR_TOT_ITEM"],
        'limites_tamanho': {
            "DESC_MAT_SERV": 700,
            "UNID_MED": 50,
            "NF": 20,
            "OBS": 250,
            "COD_MAT_SERV": 12
        }
    },
    'modulo_receitas': {
        'cabecalho_str': 'D;COD_OS;COD_UNIDADE;COD_CONTRATO;ANO_MES_REF;BANCO;AGENCIA;CONTA_CORRENTE;REC_CONT_GES_FIXA;REC_CONT_GES_VARIAVEL;REC_TA_ADIC_CUSTEIO;REC_TA_ADIC_INVEST;REC_APLIC_FINANCEIRA;REC_REEMB_DESPESAS;REC_RECURSOS_EXTERNOS;REC_REC_EXTRAS;REC_OUTRAS_RECEITAS;REC_CONT_GES_VARIAVEL_2;REC_CONT_GES_VARIAVEL_3;REC_REP_SUS_AIH;REC_REP_SUS_AMB;REC_REP_SUS_INTEGRASUS',
        'datas_abreviadas': ['ANO_MES_REF'],
        'datas_completas': [],
        'campos_obrigatorios': ["D", "COD_OS", "COD_UNIDADE", "COD_CONTRATO", "ANO_MES_REF", "BANCO", "AGENCIA", "CONTA_CORRENTE", "REC_CONT_GES_FIXA", "REC_CONT_GES_VARIAVEL", "REC_TA_ADIC_CUSTEIO", "REC_TA_ADIC_INVEST", "REC_APLIC_FINANCEIRA", "REC_REEMB_DESPESAS", "REC_RECURSOS_EXTERNOS", "REC_REC_EXTRAS", "REC_OUTRAS_RECEITAS", "REC_CONT_GES_VARIAVEL_2", "REC_CONT_GES_VARIAVEL_3", "REC_REP_SUS_AIH", "REC_REP_SUS_AMB", "REC_REP_SUS_INTEGRASUS"],
        'campos_monetarios': ['REC_CONT_GES_FIXA', 'REC_CONT_GES_VARIAVEL', 'REC_TA_ADIC_CUSTEIO', 'REC_TA_ADIC_INVEST', 'REC_APLIC_FINANCEIRA', 'REC_REEMB_DESPESAS', 'REC_RECURSOS_EXTERNOS', 'REC_REC_EXTRAS', 'REC_OUTRAS_RECEITAS', 'REC_CONT_GES_VARIAVEL_2', 'REC_CONT_GES_VARIAVEL_3', 'REC_REP_SUS_AIH', 'REC_REP_SUS_AMB', 'REC_REP_SUS_INTEGRASUS'],
        'limites_tamanho': {}
    },
    'modulo_folha_de_pagamento': {
        'cabecalho_str': 'COD_OS;CPF;ANO_MES_REF;CONTRATO;COD_UNIDADE;CARGA_HORARIA;TIPO_VINCULO;ANO_MES_COMP;CNPJ;PERC_RATEIO;DT_INICIO_LICENCA;DT_FIM_LICENCA;SALARIO_BASE;PROVENTO_FERIAS;PROVENTO_13_SALARIO;PROVENTO_REEMBOLSO;PROVENTO_HORA_EXTRA;PROVENTO_PLANTAO;PROVENTO_INSALUBRIDADE;PROVENTO_PERICULOSIDADE;PROVENTO_ADICIONAL_NOTURNO;PROVENTO_GRATIFICACAO;PREMIACAO;PROVENTO_BONIFICACAO;PROVENTO_SALARIO_FAMILIA;PROVENTO_FOLHA_BOLSA_AUXILIO;PROVENTO_GRATIFICACOES;PROVENTO_LICENCA_MATERINADE;DESCANSO_SEMANAL_REMUNERADO;DESCONTO_FALTA;DESCONTO_ATRASO;DESCONTO_ADIANTAMENTO;DESCONTO_CONTRIBUICAO_SINDICAL;DESCONTO_VALE_ALIMENTACAO;DESCONTO_VALE_REFEICAO;DESCONTO_VALE_TRANSPORTE;DESCONTO_VALE_COMBUSTIVEL;DESCONTO_PENSAO_ALIMENTACAO;DESCONTO_CONVENIO_MEDICO;DESCONTO_FOLHA_EMPR_CONSIG;DESCONTO_INSS;DESCONTO_IRRF;ENCARGO_INSS_BASE;DESCONTO_2a_VIA_CARTAO;DESCONTO_MULTA;ENCARGO_FGTS_BASE;DESCONTO_JUDICIAL;ENCARGO_PIS_BASE;ENCARGO_INSS;DESCONTO_INSUFICIENCIA_SALDO;ENCARGO_FGTS;DESCONTO_ISSQN;ENCARGO_PIS;ENCARGO_SESI_SESC;ENCARGO_SENAI_SENAC;ENCARGO_INCRA;ENCARGO_SALARIO_EDUCACAO;ENCARGO_SEGURO_ACIDENTE;ENCARGO_SEBRAE;BENEFICIO_VALE_ALIMENTACAO;BENEFICIO_VALE_REFEICAO;BENEFICIO_VALE_TRANSPORTE;BENEFICIO_VALE_COMBUSTIVEL;BENEFICIO_AUXILIO_CRECHE;BENEFICIO_PLANO_SAUDE;BENEFICIO_MOBILIDADE;RESCISAO_FERIAS;BENEFICIO_SEGURO_VIDA;BENEFICIO_PREV_PRIVADA;RESCISAO_FERIAS_ABONO;RESCISAO_13_SALARIO;RESCISAO_AVISO_PREVIO;PROVENTO_ASSIST_COMPL_UNIAO;RESCISAO_AVISO_PREV_INDENIZADO;PROVENTO_INSUFICIENCIA_SALDO;RESCISAO_13_INDENIZADO;PROVENTO_HONORARIOS;RESCISAO_MULTA_FGTS;REMUNERACAO_LIQUIDA;DESPESA_TOTAL',
        'datas_abreviadas': ['ANO_MES_REF', 'ANO_MES_COMP'],
        'datas_completas': [],
        'campos_obrigatorios': [
          "COD_OS", "CPF", "ANO_MES_REF", "CONTRATO", "COD_UNIDADE", "CARGA_HORARIA",
          "TIPO_VINCULO", "ANO_MES_COMP", "CNPJ", "SALARIO_BASE", "PROVENTO_FERIAS", "PROVENTO_13_SALARIO",
          "PROVENTO_REEMBOLSO", "PROVENTO_HORA_EXTRA", "PROVENTO_PLANTAO",
          "PROVENTO_INSALUBRIDADE", "PROVENTO_PERICULOSIDADE", "PROVENTO_ADICIONAL_NOTURNO",
          "PROVENTO_GRATIFICACAO", "PREMIACAO", "PROVENTO_BONIFICACAO", "PROVENTO_SALARIO_FAMILIA",
          "PROVENTO_FOLHA_BOLSA_AUXILIO", "PROVENTO_GRATIFICACOES", "PROVENTO_LICENCA_MATERINADE",
          "DESCANSO_SEMANAL_REMUNERADO", "DESCONTO_FALTA", "DESCONTO_ATRASO", "DESCONTO_ADIANTAMENTO",
          "DESCONTO_CONTRIBUICAO_SINDICAL", "DESCONTO_VALE_ALIMENTACAO", "DESCONTO_VALE_REFEICAO",
          "DESCONTO_VALE_TRANSPORTE", "DESCONTO_VALE_COMBUSTIVEL", "DESCONTO_PENSAO_ALIMENTACAO",
          "DESCONTO_CONVENIO_MEDICO", "DESCONTO_FOLHA_EMPR_CONSIG", "DESCONTO_INSS", "DESCONTO_IRRF",
          "ENCARGO_INSS_BASE", "ENCARGO_FGTS_BASE", "ENCARGO_PIS_BASE", "ENCARGO_INSS",
          "ENCARGO_FGTS", "ENCARGO_PIS", "ENCARGO_SESI_SESC", "ENCARGO_SENAI_SENAC",
          "ENCARGO_INCRA", "ENCARGO_SALARIO_EDUCACAO", "ENCARGO_SEGURO_ACIDENTE", "ENCARGO_SEBRAE",
          "BENEFICIO_VALE_ALIMENTACAO", "BENEFICIO_VALE_REFEICAO", "BENEFICIO_VALE_TRANSPORTE",
          "BENEFICIO_VALE_COMBUSTIVEL", "BENEFICIO_AUXILIO_CRECHE", "BENEFICIO_PLANO_SAUDE",
          "BENEFICIO_MOBILIDADE", "RESCISAO_FERIAS", "RESCISAO_FERIAS_ABONO", "RESCISAO_13_SALARIO", "RESCISAO_AVISO_PREVIO",
          "RESCISAO_AVISO_PREV_INDENIZADO", "RESCISAO_13_INDENIZADO", "RESCISAO_MULTA_FGTS", "REMUNERACAO_LIQUIDA",
          "DESPESA_TOTAL"
        ],
        'campos_monetarios': [
            "SALARIO_BASE", "PROVENTO_FERIAS", "PROVENTO_13_SALARIO",
            "PROVENTO_REEMBOLSO", "PROVENTO_HORA_EXTRA", "PROVENTO_PLANTAO",
            "PROVENTO_INSALUBRIDADE", "PROVENTO_PERICULOSIDADE", "PROVENTO_ADICIONAL_NOTURNO",
            "PROVENTO_GRATIFICACAO", "PREMIACAO", "PROVENTO_BONIFICACAO", "PROVENTO_SALARIO_FAMILIA",
            "PROVENTO_FOLHA_BOLSA_AUXILIO", "PROVENTO_GRATIFICACOES", "PROVENTO_LICENCA_MATERINADE",
            "DESCANSO_SEMANAL_REMUNERADO", "DESCONTO_FALTA", "DESCONTO_ATRASO", "DESCONTO_ADIANTAMENTO",
            "DESCONTO_CONTRIBUICAO_SINDICAL", "DESCONTO_VALE_ALIMENTACAO", "DESCONTO_VALE_REFEICAO",
            "DESCONTO_VALE_TRANSPORTE", "DESCONTO_VALE_COMBUSTIVEL", "DESCONTO_PENSAO_ALIMENTACAO",
            "DESCONTO_CONVENIO_MEDICO", "DESCONTO_FOLHA_EMPR_CONSIG", "DESCONTO_INSS", "DESCONTO_IRRF",
            "ENCARGO_INSS_BASE", "DESCONTO_2a_VIA_CARTAO", "DESCONTO_MULTA", "ENCARGO_FGTS_BASE",
            "DESCONTO_JUDICIAL", "ENCARGO_PIS_BASE", "ENCARGO_INSS", "DESCONTO_INSUFICIENCIA_SALDO",
            "ENCARGO_FGTS", "DESCONTO_ISSQN", "ENCARGO_PIS", "ENCARGO_SESI_SESC", "ENCARGO_SENAI_SENAC",
            "ENCARGO_INCRA", "ENCARGO_SALARIO_EDUCACAO", "ENCARGO_SEGURO_ACIDENTE", "ENCARGO_SEBRAE",
            "BENEFICIO_VALE_ALIMENTACAO", "BENEFICIO_VALE_REFEICAO", "BENEFICIO_VALE_TRANSPORTE",
            "BENEFICIO_VALE_COMBUSTIVEL", "BENEFICIO_AUXILIO_CRECHE", "BENEFICIO_PLANO_SAUDE",
            "BENEFICIO_MOBILIDADE", "RESCISAO_FERIAS", "BENEFICIO_SEGURO_VIDA", "BENEFICIO_PREV_PRIVADA",
            "RESCISAO_FERIAS_ABONO", "RESCISAO_13_SALARIO", "RESCISAO_AVISO_PREVIO",
            "PROVENTO_ASSIST_COMPL_UNIAO", "RESCISAO_AVISO_PREV_INDENIZADO", "PROVENTO_INSUFICIENCIA_SALDO",
            "RESCISAO_13_INDENIZADO", "PROVENTO_HONORARIOS", "RESCISAO_MULTA_FGTS", "REMUNERACAO_LIQUIDA",
            "DESPESA_TOTAL"
        ],
        'limites_tamanho': {
            "PERC_RATEIO": 100
        }
    },
    'modulo_provisionamento': {
        'cabecalho_str': 'COD_OS;CPF;ANO_MES_REFERENCIA;CONTRATO;COD_UNIDADE;TIPO_VINCULO;ANO_MES_COMPETENCIA;CNPJ;13_SALARIO_GRUPO_B;ABONO_DE_FERIAS_GRUPO_B;FERIAS_PROPORCIONAIS_GRUPO_B;FERIAS_INTEGRAIS_GRUPO_B;AVISO_PREVIO_GRUPO_C;AVISO_PREVIO_INDENIZADO_GRUPO_C;13_SALARIO_GRUPO_C;FERIAS_E_ABONO_CONSTITUCIONAL_GRUPO_C;MULTA_FGTS_GRUPO_D;INCIDENCIA_DE_A_SOBRE_B_MAIS_C_GRUPO_E;FERIAS_BAIXA;13_SALARIO_BAIXA;AVISO_PREVIO_RESCISAO_BAIXA;AVISO_PREVIO_INDENIZADO_RESCISAO_BAIXA;13_SALARIO_RESCISAO_BAIXA;FERIAS_E_ABONO_RESCISAO_BAIXA;MULTA_FGTS_RESCISAO_BAIXA',
        'datas_abreviadas': ['ANO_MES_REF', 'ANO_MES_COMP'],
        'datas_completas': [],
        'campos_obrigatorios': ["COD_OS", "CPF", "ANO_MES_REFERENCIA", "CONTRATO", "COD_UNIDADE", "TIPO_VINCULO", "ANO_MES_COMPETENCIA", "CNPJ", "13_SALARIO_GRUPO_B", "ABONO_DE_FERIAS_GRUPO_B", "FERIAS_PROPORCIONAIS_GRUPO_B", "FERIAS_INTEGRAIS_GRUPO_B", "AVISO_PREVIO_GRUPO_C", "AVISO_PREVIO_INDENIZADO_GRUPO_C", "13_SALARIO_GRUPO_C", "FERIAS_E_ABONO_CONSTITUCIONAL_GRUPO_C", "MULTA_FGTS_GRUPO_D", "INCIDENCIA_DE_A_SOBRE_B_MAIS_C_GRUPO_E", "FERIAS_BAIXA", "13_SALARIO_BAIXA", "AVISO_PREVIO_RESCISAO_BAIXA", "AVISO_PREVIO_INDENIZADO_RESCISAO_BAIXA", "13_SALARIO_RESCISAO_BAIXA", "FERIAS_E_ABONO_RESCISAO_BAIXA", "MULTA_FGTS_RESCISAO_BAIXA"],
        'campos_monetarios': ["13_SALARIO_GRUPO_B", "ABONO_DE_FERIAS_GRUPO_B", "FERIAS_PROPORCIONAIS_GRUPO_B", "FERIAS_INTEGRAIS_GRUPO_B", "AVISO_PREVIO_GRUPO_C", "AVISO_PREVIO_INDENIZADO_GRUPO_C", "13_SALARIO_GRUPO_C", "FERIAS_E_ABONO_CONSTITUCIONAL_GRUPO_C", "MULTA_FGTS_GRUPO_D", "INCIDENCIA_DE_A_SOBRE_B_MAIS_C_GRUPO_E", "FERIAS_BAIXA", "13_SALARIO_BAIXA", "AVISO_PREVIO_RESCISAO_BAIXA", "AVISO_PREVIO_INDENIZADO_RESCISAO_BAIXA", "13_SALARIO_RESCISAO_BAIXA", "FERIAS_E_ABONO_RESCISAO_BAIXA", "MULTA_FGTS_RESCISAO_BAIXA"],
        'limites_tamanho': {}
    },
    'modulo_desligamento_em_lote': {
        'cabecalho_str': 'ID;COD_OS;CPF;VINCULACAO;DATA_DEMISSAO',
        'datas_abreviadas': [],
        'datas_completas': ["DATA_DEMISSAO"],
        'campos_obrigatorios': ["ID", "COD_OS", "CPF", "VINCULACAO", "DATA_DEMISSAO"],
        'campos_monetarios': [],
        'limites_tamanho': {}
    },
}
