LISTA_MODULOS = ['despesas', 'contratosdeterceiros', 'receitas', 'benspatrimoniados', 'saldos', 'itensdenotafiscal']

LISTA_ACOES = ['alteracao', 'exclusao', 'inclusao']

LISTA_ATRIBUTOS_SALDOS = [
    'VALOR EM CONTA CORRENTE', 'APLICACAO FINANCEIRA', 'PROVISAO', 'VALOR EM ESPECIE'
]

LISTA_ATRIBUTOS_DESPESAS = [
    'VALOR PAGO', 'VALOR DO DOCUMENTO', 'RUBRICA', 'DESCRICAO', 'CONTA CORRENTE',
    'UNIDADE', 'IDENTIFICADOR BANCARIO', 'NUMERO DO DOCUMENTO',
    'CNPJ', 'RAZAO SOCIAL', 'DATA DE EMISSAO', 'TIPO DE DOCUMENTO', 'CPF', 'NOME',
    'DATA DE VENCIMENTO', 'DATA DE PAGAMENTO', 'DATA DE APURACAO', 'TIPO DE DESPESA',
    'SERIE', 'NUMERO DE PARCELAS', 'CODIGO FISCAL', 'PARCELA PAGA'
]

LISTA_ATRIBUTOS_CONTRATOS_DE_TERCEIROS = [
    'NOME DO ARQUIVO', 'SERVICO', 'UNIDADE', 'VIGENCIA', 'VALOR MENSAL', 'RAZAO SOCIAL',
    'CNPJ', 'CPF', 'NOME', 'MES INICIO', 'MES FIM', 'ANO INICIO', 'ANO FIM'
]

LISTA_ATRIBUTOS_BENS_PATRIMONIADOS = [
    'NOME ARQUIVO IMAGEM', 'VIDA UTIL', 'VINCULACAO', 'SETOR DESTINO', 'NOTA FISCAL', 'DESCRICAO',
    'TIPO', 'CONTROLE', 'RAZAO SOCIAL', 'CNPJ', 'QUANTIDADE', 'VALOR', 'UNIDADE'
]

LISTA_ATRIBUTOS_ITENS_DE_NOTA_FISCAL = [
    'NUMERO DA NOTA FISCAL', 'CODIGO DO MATERIAL', 'CODIGO DO SERVICO', 'DESCRICAO', 'UNIDADE DE MEDIDA',
    'QUANTIDADE', 'VALOR UNITARIO', 'VALOR TOTAL', 'MES DE REFERENCIA', 'ANO DE REFERENCIA',
    'FORNECEDOR', 'OBSERVACAO'
]

LISTA_ATRIBUTOS_RECEITAS = [
    'CONTRATO DE GESTAO PARTE FIXA', 'REPASSE CONTRATO DE GESTAO PARTE VARIAVEL 1',
    'REPASSE CONTRATO DE GESTAO PARTE VARIAVEL 2', 'REPASSE CONTRATO DE GESTAO PARTE VARIAVEL 3',
    'TERMO ADITIVO ADICIONAL CUSTEIO', 'TERMO ADITIVO ADICIONAL INVESTIMENTO',
    'RESULTADO DE APLICACAO FINANCEIRA', 'ESTORNO DE DESPESAS',
    'OBTENCAO DE RECURSOS EXTERNOS', 'RETORNO DE EMPRESTIMO REALIZADO A OUTRO CONTRATO',
    'EMPRESTIMO TOMADO DE OUTRO CONTRATO', 'TRANSFERENCIAS ENTRE CONTAS DE PROVISIONAMENTO E EXECUCAO',
    'TRANSFERENCIA DE PROVISIONAMENTO DE COLABORADORES ORIUNDOS DE OUTRO CONTRATO E OU UNIDADE'
]